Vsync set to be always on.
From the forums it was told that setting vsync to be always one makes decoding faster.
Although enabling this patch you will get the following error on xbmc.log (EGL doesn't support vsync at all) -

  ERROR: EGL Error: Could not set vsync
  ERROR: GLES: Vertical Blank Syncing unsupported